name: tdd

on: [push]

env:
  PYTHON_VERSION: '3.x'
  TEST_REPORT: report.html

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v2
      with:
        # セマンティックバージョン範囲の構文または Python バージョンの正確なバージョン
        python-version: ${{ env.PYTHON_VERSION }}
        # オプション - x64 または x86 アーキテクチャ、デフォルトは x64
        architecture: 'x64' 
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-html pytest-cov pytest-datadir
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # Python 構文エラーまたは未定義の名前がある場合はビルドを停止する
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zeroはすべてのエラーを警告として扱う。 GitHubのエディタの幅は127文字
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest . --html=$TEST_REPORT
    - name: Arcive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: outputs
        path: |
              ${{ env.TEST_REPORT }}
              assets
              
